disp('hello matlab on open mind')
1+1

imdsTrain = imageDatastore('data/Training', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');

imdsTest = imageDatastore('data/Testing', ...
       'IncludeSubfolders',true, ...
       'LabelSource','foldernames');

net = alexnet;